FileVersion = 1
Dependencies = {corlib = "*", SDL3 = "*", corlib = "*"}

[Project]
Name = "SDL3_image"
TargetType = "BeefLib"
StartupObject = "SDL3_image.Program"

[Configs.Debug.Win32]
LibPaths = ["$(ProjectDir)/dist/SDL3_image-3.2.4/lib/x86/SDL3_image.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/SDL3_image-3.2.4/lib/x86/*.dll\")"]

[Configs.Debug.Win64]
LibPaths = ["$(ProjectDir)/dist/SDL3_image-3.2.4/lib/x64/SDL3_image.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/SDL3_image-3.2.4/lib/x64/*.dll\")"]

[Configs.Release.Win32]
LibPaths = ["$(ProjectDir)/dist/SDL3_image-3.2.4/lib/x86/SDL3_image.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/SDL3_image-3.2.4/lib/x86/*.dll\")"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)/dist/SDL3_image-3.2.4/lib/x64/SDL3_image.lib"]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/SDL3_image-3.2.4/lib/x64/*.dll\")"]
